### ISSUE TITLE
[node-gyp] fatal error: 'chakra_ttd.h'

### ISSUE THREAD

**Issue by mrmlnc** [nodejs/node-chakracore#417]
* **Version**: 8.6.0 (x64)
* **Platform**: macOS (10.12.6)
* **Subsystem**:

**Source code**: https://github.com/mrmlnc/scandir-native
**Full Error**:

```
> node-gyp configure build

  CXX(target) Release/obj.target/addon/src/cpp/addon.o
In file included from ../src/cpp/addon.cc:1:
In file included from ../node_modules/nan/nan.h:49:
/usr/local/nvs/chakracore/8.6.0/x64/include/node/node.h:99:10: fatal error: 'chakra_ttd.h'
      file not found
#include "chakra_ttd.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/addon/src/cpp/addon.o] Error 1
```

Works fine with `8.4.0`, because `v8.h` has no `#include "chakra_ttd.h"`. But also works fine with `8.6.0` on the Windows.

**Comment by joaocgreis** [comment]
Possible fix: https://github.com/nodejs/node-chakracore/pull/421

**Comment by joaocgreis** [comment]
Fix landed, the next nightly should have it. Thanks for reporting @mrmlnc !

**Comment by mrmlnc** [comment]
Thanks for your work 🌮
