### ISSUE TITLE
Cannot build from Source - ChakraCore.h not found

### ISSUE THREAD

**Issue by neogeno** [nodejs/node-chakracore#512]
* **Version**: master node-chakracore
* **Platform**: Mac OS 10.13.4
* **Subsystem**:

Followed the ./configure and make procedure in your readme. After typing make I get

../deps/chakrashim/include/v8.h:67:10: fatal error: 'ChakraCore.h' file not found

**Comment by MSLaguana** [comment]
That's odd, `ChakraCore.h` should be part of the repository that you cloned. Do you see a `deps/chakrashim/core/lib/Jsrt/ChakraCore.h`?

**Comment by MSLaguana** [comment]
One thing I will note: there is currently a build break in the master branch to do with ICU, but that would be a very different error. I suggest that you checkout the `chakracore-master` branch if you want to build from source at the moment.

**Comment by neogeno** [comment]
Hi, Yes the deps/chakrashim/core/lib/Jsrt/ChakraCore.h is present but it seems make cannot find it when it searches for headers. How can I manually add the path to be searched to the make process then?

**Comment by MSLaguana** [comment]
Hmm, I just reproduced this error. Looks like what's actually going on is a dependency on chakracore.h has made its way into the node sources, not the chakrashim sources. I'm not sure why this hasn't affected our CI. @kfarnung do you know what might be causing `async_wrap.cc` to take a dependency on `chakracore.h` which fails now, considering the `#include chakracore.h` in `v8.h` has been there for years?

```
In file included from ../src/node_persistent.h:6:0,
                 from ../src/base_object.h:27,
                 from ../src/async_wrap.h:27,
                 from ../src/async_wrap-inl.h:27,
                 from ../src/async_wrap.cc:22:
../deps/chakrashim/include/v8.h:67:24: fatal error: ChakraCore.h: No such file or directory
```

**Comment by kfarnung** [comment]
I haven't run into this on Windows or Linux Mint 18.3, I kicked off a build on my Mac so I'll see what the result is there.

@MSLaguana what configuration are you able to reproduce with?

**Comment by kfarnung** [comment]
My Mac was able to build without issue on 10.13.5 beta (I believe it worked on 10.13.4 as well).  One thing to note is that the `ChakraCore.h` file used is actually the copy that gets dropped in `deps/chakrashim/include/ChakraCore.h` alongside `v8.h`.  Can you both check to make sure that file is there?  Have you tried doing a full clean using `git clean -xdf` in your repo?

**Comment by kfarnung** [comment]
(Sorry for the spam)

I just remembered that there was a Linux and Mac build break I discovered earlier today, but it manifested as a ChakraCore build break due to a new ICU change (64211405dab824a570e52d000891c49415cc42b8) that required a ChakraCore fix (29d44c28578d58ae92a40b4112481766e066b2ec).

@neogeno Can you try pulling the latest master and build again?  I suspect the issue might already be fixed.  If ChakraCore fails to build then I don't think `ChakraCore.h` will get dropped alongside `v8.h` which would explain that error message.

**Comment by MSLaguana** [comment]
@kfarnung I was trying to repro in WSL in a fresh checkout. I was aware of the ICU change breaking things, but the build didn't get that far; it was breaking when building some node sources, rather than chakracore/chakrashim sources.

**Comment by kfarnung** [comment]
Can you run `ls deps/chakrashim/include`?

**Comment by MSLaguana** [comment]
It seems that I only have v8 headers in there, not the chakracore header. It somewhat looks to me like the dependency of node-chakracore on chakracore (/chakrashim) is missing, so it isn't trying to build chakrashim before it tries to build the node parts, and so it fails.

**Comment by rhuanjl** [comment]
Just tried and and a clean checkout of the current master branch currently fails to build with this issue on macOS, however simply copy+pasting chakracore.h, chakracommon.h and chakradebug.h into the correct folder resulted in the build completing.

**Comment by kfarnung** [comment]
I believe I have a fix, please try it out if you can:  https://github.com/nodejs/node-chakracore/pull/531

EDIT: To pull in the fix:
```console
$ curl -L https://github.com/nodejs/node-chakracore/pull/531.patch | git am --whitespace=fix
$ ./configure --engine=chakracore
$ make
```

It seems to be working for me. I even let it fail without the patch, applied it, ran configure again, and ran make. So far, so good.
