### PR TITLE
tools: add chakra_tdd.h to install.py

### LINKED ISSUE #417: [node-gyp] fatal error: 'chakra_ttd.h'
* **Version**: 8.6.0 (x64)
* **Platform**: macOS (10.12.6)
* **Subsystem**:

**Source code**: https://github.com/mrmlnc/scandir-native
**Full Error**:

```
> node-gyp configure build

  CXX(target) Release/obj.target/addon/src/cpp/addon.o
In file included from ../src/cpp/addon.cc:1:
In file included from ../node_modules/nan/nan.h:49:
/usr/local/nvs/chakracore/8.6.0/x64/include/node/node.h:99:10: fatal error: 'chakra_ttd.h'
      file not found
#include "chakra_ttd.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/addon/src/cpp/addon.o] Error 1
```

Works fine with `8.4.0`, because `v8.h` has no `#include "chakra_ttd.h"`. But also works fine with `8.6.0` on the Windows.

### PR DESCRIPTION
**Pull request by joaocgreis**
`chakra_tdd.h` was added to the sources in https://github.com/nodejs/node-chakracore/pull/397. This adds it to install.py to be included in the headers package.

Refs: https://github.com/nodejs/node-chakracore/pull/397
Fixes: https://github.com/nodejs/node-chakracore/issues/417

cc @mike-kaufman @mrkmarron

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

tools

### CODE REVIEW

**Comment by joaocgreis** [comment]
CI: https://ci.nodejs.org/view/All/job/chakracore-test-pull-request/156/
Test build: https://nodejs.org/download/test/v9.0.0-test20171101117809f8cc/

**Review by gireeshpunathil — APPROVED** [review]
how about following the single line custom for single file inclusions? (for example L174 and L194)

**Review by mike-kaufman — APPROVED** [review]

**Comment by joaocgreis** [comment]
Updated, single line sounds good for now.

**Comment by joaocgreis** [comment]
Landed in https://github.com/nodejs/node-chakracore/commit/fca1d9fdb48c8279703ba244023d46126fc5c9bc
